import{a as h,S as L,i as n}from"./assets/vendor-DMjJPMAs.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();h.defaults.baseURL="https://pixabay.com/api/";const A={key:"49327646-fcd0425046884d30268cb7003",image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15};async function p(s,t=1){try{const o=await h.get("/",{params:{...A,q:s,page:t}});return{images:o.data.hits,totalResults:o.data.totalHits}}catch(o){return console.error(o),{images:[],totalResults:0}}}async function y(s){if(!s.length)return;const t=document.querySelector(".gallery"),o=s.map(({webformatURL:e,largeImageURL:r,tags:l,likes:f,views:b,comments:F,downloads:w})=>`
        <li class="galleryCard">
          <a href="${r}">
            <img class="img" src="${e}" alt="${l}">
          </a>
          <ul class="attributesList">
            <li class="attributesItem"><span class="attributesLabel">Likes</span><br>${f}</li>
            <li class="attributesItem"><span class="attributesLabel">Views</span><br>${b}</li>
            <li class="attributesItem"><span class="attributesLabel">Comments</span><br>${F}</li>
            <li class="attributesItem"><span class="attributesLabel">Downloads</span><br>${w}</li>
          </ul>
        </li>
      `).join("");t.insertAdjacentHTML("beforeend",o),await new Promise(e=>requestAnimationFrame(e));let a;a?a.refresh():a=new L(".gallery a",{captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250})}const g=document.querySelector(".form"),C=document.querySelector(".gallery"),u=document.querySelector(".loader"),d=document.querySelector(".load-more");let i=1,m=0,c="";g.addEventListener("submit",async s=>{if(s.preventDefault(),c=s.target.elements.search.value.trim(),!c){n.show({message:"Enter a search term!",position:"topRight"});return}C.innerHTML="",i=1,d.classList.add("visually-hidden"),u.style.display="block";try{const{images:t,totalResults:o}=await p(c,i);!t||t.length===0?n.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#EF4040",messageColor:"#FAFAFB",iconColor:"#FAFAFB"}):(y(t),m=Math.ceil(o/15),i<m&&d.classList.remove("visually-hidden"))}catch(t){console.error("Error while retrieving images:",t),n.show({message:"An error occurred while searching. Please try again!",position:"topRight",maxWidth:"400px",backgroundColor:"#EF4040",messageColor:"#FAFAFB",iconColor:"#FAFAFB"})}finally{u.style.display="none"}g.reset()});d.addEventListener("click",async()=>{i+=1,u.style.display="block";try{const{images:s}=await p(c,i);y(s);const t=document.querySelector(".galleryCard");if(t){const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}i>=m&&(d.classList.add("visually-hidden"),n.show({message:"We're sorry, but you've reached the end of search results.",maxWidth:"400px",position:"topRight"}))}catch(s){console.error("Error while retrieving more images:",s),n.show({message:"An error occurred while loading more images. Please try again!",position:"topRight",width:400,backgroundColor:"#EF4040",messageColor:"#FAFAFB",iconColor:"#FAFAFB"})}finally{u.style.display="none"}});
//# sourceMappingURL=index.js.map
